# Site settings
# YAML cheat sheet: https://quickref.me/yaml

title: "Sveltia Test"
description: "A template for building a fast Eleventy blog with Sveltia CMS"
url: "https://sveltia-cms.nothing.com"
